// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqoxodcvbdlfquwodujr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhxb3hvZGN2YmRsZnF1d29kdWpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgwMTEyNjEsImV4cCI6MjA4MzU4NzI2MX0.-_WHLzr3gGWgZNN8mSdZ_6yzgynxqNqXh2ajSYJwmCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});